DROP DATABASE ADMINISTRADOR;
CREATE DATABASE ADMINISTRADOR;
USE ADMINISTRADOR;
CREATE TABLE ADMINISTRADOR(

ID INT  NOT NULL auto_increment,
USUARIO VARCHAR(40)  NOT NULL,
CONTRASEÑA VARCHAR(40)  NOT NULL,
CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY (ID)
);

CREATE TABLE RECEPCIONISTA (

ID INT NOT NULL auto_increment,
USUARIO VARCHAR(40) NOT NULL,
CONTRASEÑA VARCHAR(40) NOT NULL,
CONSTRAINT PK_RECEPCIONISTA PRIMARY KEY (ID)

);

CREATE TABLE CLIENTE (
ID INT NOT NULL auto_increment,
NOMBRE VARCHAR(40) NOT NULL,
APELLIDO VARCHAR(40) NOT NULL,
DIRECCION VARCHAR(40),
CONTRASEÑA VARCHAR(40) NOT NULL,
CORREO VARCHAR(50) NOT NULL,
SEXO VARCHAR(10),
USUARIO VARCHAR(50) NOT NULL,
ID_ADMINISTRADOR INT ,
CONSTRAINT PK_CLIENTE PRIMARY KEY(ID),
CONSTRAINT FK_ADMINISTRADOR_CLIENTE FOREIGN KEY (ID_ADMINISTRADOR) REFERENCES ADMINISTRADOR(ID) ON DELETE CASCADE

);
select * from cliente;

CREATE TABLE PAQUETE(
ID INT NOT NULL auto_increment,
TIPO_PAQUETE VARCHAR(40),
UBICACION VARCHAR(60),
DESCRIPCION VARCHAR(200),
FECHA DATE NOT NULL,
ESTADO VARCHAR(20),
ID_ADMINISTRADOR int,
ID_CLIENTE INT,
CONSTRAINT PK_PAQUETE PRIMARY KEY (ID),
CONSTRAINT FK_ADMINISTRADOR_PAQUETE FOREIGN KEY (ID_ADMINISTRADOR) REFERENCES ADMINISTRADOR(ID) ON DELETE CASCADE,
CONSTRAINT FK_CLIENTE_PAQUETE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID) ON DELETE CASCADE
);

CREATE TABLE CORREO(
ID INT NOT NULL auto_increment,
ID_CLIENTE INT ,
ID_ADMINISTRADOR INT,
DESCRIPCION VARCHAR(500),

CONSTRAINT PK_CORREO PRIMARY KEY (ID),
CONSTRAINT FK_ADMINISTRADOR_CORREO FOREIGN KEY (ID_ADMINISTRADOR) REFERENCES ADMINISTRADOR(ID) ON DELETE CASCADE,
CONSTRAINT FK_CLIENTE_CORREO FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID) ON DELETE CASCADE
);

CREATE TABLE MODIFICACIONES_RECEPCIONISTAS(
ID INT NOT NULL auto_increment,
ID_PAQUETE INT NOT NULL,
ID_RECEPCIONISTA INT NOT NULL,
FECHA TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT PK_MODIFICACIONES_R PRIMARY KEY (ID),
CONSTRAINT FK_PAQUETE_MR FOREIGN KEY (ID_PAQUETE) REFERENCES PAQUETE(ID) ON DELETE CASCADE,
CONSTRAINT FK_RECEPCIONISTA_MR FOREIGN KEY (ID_RECEPCIONISTA) REFERENCES RECEPCIONISTA(ID) ON DELETE CASCADE
);

CREATE TABLE MODIFICACIONES_ADMINISTRADOR(
ID INT NOT NULL auto_increment,
ID_PAQUETE INT NOT NULL,
ID_ADMINISTRADOR INT NOT NULL,
FECHA TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT PK_MODIFICACIONES_A PRIMARY KEY (ID),
CONSTRAINT FK_ADMINISTRADOR_MA FOREIGN KEY (ID_ADMINISTRADOR) REFERENCES ADMINISTRADOR(ID) ON DELETE CASCADE,
CONSTRAINT FK_PAQUETE_MA FOREIGN KEY (ID_PAQUETE) REFERENCES PAQUETE(ID) ON DELETE CASCADE

);

INSERT INTO ADMINISTRADOR(USUARIO, CONTRASEÑA) VALUES('ADMIN','12345');
INSERT INTO RECEPCIONISTA(USUARIO, CONTRASEÑA) VALUES ('RECEP', '12345');
SELECT * FROM CLIENTE;
SELECT * FROM PAQUETE WHERE ESTADO = 'Disponible';
INSERT INTO PAQUETE(TIPO_PAQUETE,UBICACION,DESCRIPCION,FECHA,ESTADO, ID_CLIENTE) VALUES('Frágil','Calle C Santo Domingo Este','no se','2018-8-9','Disponible',1);
INSERT INTO PAQUETE(TIPO_PAQUETE,UBICACION,DESCRIPCION,FECHA,ESTADO, ID_CLIENTE) VALUES('Frágil','Calle D Santo Domingo Este','No especificada','2018-8-9','Disponible',3);
INSERT INTO PAQUETE(TIPO_PAQUETE,UBICACION,DESCRIPCION,FECHA,ESTADO, ID_CLIENTE) VALUES('Diponible','lejos','no se','2018-1-5','Entregado',2);
INSERT INTO PAQUETE(TIPO_PAQUETE,UBICACION,DESCRIPCION,FECHA,ESTADO) VALUES('Diponible','lejos','no se','2018-3-5','Disponible');
select * from cliente where sexo = 'hombre';
select * from cliente;
SELECT * FROM CLIENTE WHERE SEXO = 'Otros';
INSERT INTO CLIENTE(NOMBRE,APELLIDO,DIRECCION,CONTRASEÑA,CORREO,SEXO,USUARIO) VALUES('JUAN', 'JOSE','NO TIENE', '123','ASDADSA', 'Hombre','Hombre');
INSERT INTO CLIENTE(NOMBRE,APELLIDO,DIRECCION,CONTRASEÑA,CORREO,SEXO,USUARIO) VALUES('asdad', 'Jasdasdas','NO TIENE', '123','ASDADSA', 'Hombre','Hombre');
INSERT INTO CLIENTE(NOMBRE,APELLIDO,DIRECCION,CONTRASEÑA,CORREO,SEXO,USUARIO) VALUES('asdffasd', 'asdfasdf','sdafsdf', '123','ASDADSA', 'Hombre','Hasdfds');
insert into cliente(nombre, apellido, direccion, contraseña, correo, usuario) values('Juan','Hernandez','Santo Domingo', '1234','a@hotmail.com','usuario');
select * from paquete;
select fecha from paquete where fecha LIKE '%" +dias+"'and fecha like '%0-"+mes+"-%';
select * from correo;
delete from paquete;
DELETE FROM RECEPCIONISTA;
DELETE FROM ADMINISTRADOR;
SELECT * FROM RECEPCIONISTA;
SELECT * FROM ADMINISTRADOR;

select * from paquete;
SELECT * FROM CLIENTE INNER JOIN PAQUETE ON CLIENTE.ID = PAQUETE.ID_CLIENTE AND PAQUETE.ESTADO = 'No Entregado'


